stages:
  - build
  - test

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

rust-latest-test:
  stage: test
  image: rust:latest
  script:
   - cargo clippy
  allow_failure: true
